CREATE TABLE diamonds
(
    Packet_No String,
    Cert_No String,
    Cts Decimal(9, 2),
    Shape String,
    Color String,
    Purity String,
    Cut String,
    Polish String,
    Symm String,
    Fls String,
    Lab String,
    Rate Decimal(10, 2),
    Disc_ Decimal(5, 2),
    Net_Rate Decimal(10, 2),
    Net_Value Decimal(12, 2),
    Report_Date String,
    Inscription String,
    Length Decimal(6, 2),
    Width Decimal(6, 2),
    Depth Decimal(6, 2),
    Depth_ Decimal(5, 2),
    Table_ Decimal(5, 2),
    CA Decimal(5, 2),
    CH Decimal(5, 2),
    PA Decimal(5, 2),
    PH Decimal(5, 2),
    Girdle String,
    Girdle_ Decimal(5, 2),
    Culet String,
    Key_To_Symbls String,
    Member_Comments String,
    Comments String,
    Star Decimal(4, 2),
    Lower Decimal(4, 2),
    Shade String,
    Table_Incl_ String,
    Black String,
    Incl__Type String,
    Open String,
    Cloud String,
    Natural String,
    Brown String,
    HA String,
    Eye_Clean String,
    Milky String,
    Extra_Facel String,
    Mines String,
    Company String,
    Phone_No String,
    Fax String,
    Country String,
    State String,
    City String,
    Video String,
    Image String,
    Download_Date_ String,
    Upload_Date String
)
ENGINE = MergeTree
ORDER BY (Download_Date_,Company ,Cert_No)